### ISSUE TITLE
Probable issue with closql's overrides on EIEIO causing recursive load error

### ISSUE THREAD

**Issue by nixmaniack** [emacscollective/closql#3]
Based on the comment https://github.com/bmag/emacs-purpose/issues/158#issuecomment-553011198 posted in the issue https://github.com/bmag/emacs-purpose/issues/158 it seems that implicit loading of `closql` causes recursive load. You may find the stacktrace on that issue but if you need any more information, I can provide that. 

Relevant Comment:
> The issues had to do with changes in `eieio` object creation interacting poorly with `closql`'s overrides and not general `autoload`ing and/or `window-purpose`.
> 
> In Spacemacs, `closql` was being loaded by `forge`, which was—in turn—loaded by the `github` layer. Disabling the `github` layer prevented the issues.

If I remove `forge` and its dependancy `closql`, I don't see the recursive load error.

Could this be an issue with closql's advices? If not, then I might take this on emacs-devel.

**Comment by tarsius** [comment]
> If I remove `forge` and its dependancy `closql`, I don't see the recursive load error.

And if you reinstall them, does the error come back? Asking because changes to macros sometimes mean that byte-code that was generated with an earlier version of Emacs or of a package is not compatible with code from a later version. Recompiling everything in the right order (dependencies first) and with no old artifacts laying around in memory or files (which could again leak into byte-code), tends to fix those issues.

**Comment by nixmaniack** [comment]
The issue persists even after doing fresh install. I removed closql and forge (rm -rf the two and delete *.elc of all packages)  and then reinstalled closql and then forge. I even upgraded from emacs27 to emacs28-HEAD and then did full reinstall of packages. I still get that recursive load error. Is there anything that I should try? Let me know if you need any more information from the running instance when issue occurs.

**Comment by tarsius** [comment]
I don't `closql` is to blame. I therefore close this and comment on https://github.com/bmag/emacs-purpose/issues/158 instead.
